<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class OffersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('offers')->insert([
            [
                'user_id' => 1,
                'title' => 'Jakis tam tytul',
                'description' => 'jakis krótki opis',
                'localization' => 'Kielce',
                'cover' => 'images/offerCovers/1W2dV4ZMkQrIoDXYB3T645GyOnNzJrvj27f7UU64.webp',
                'category_id' => '1',
                'price' => 10,
                'delivery_time' => '2-3 dni',
            ],
            [
                'user_id' => 2,
                'title' => 'Jakis tam tytul',
                'description' => 'jakis krótki opis',
                'localization' => 'Kielce',
                'cover' => 'images/offerCovers/1W2dV4ZMkQrIoDXYB3T645GyOnNzJrvj27f7UU64.webp',
                'category_id' => '1',
                'price' => 10,
                'delivery_time' => '2-3 dni',
            ],
            [
                'user_id' => 3,
                'title' => 'Jakis tam tytul',
                'description' => 'jakis krótki opis',
                'localization' => 'Kielce',
                'cover' => 'images/offerCovers/1W2dV4ZMkQrIoDXYB3T645GyOnNzJrvj27f7UU64.webp',
                'category_id' => '1',
                'price' => 10,
                'delivery_time' => '2-3 dni',
            ],
            [
                'user_id' => 4,
                'title' => 'Jakis tam tytul',
                'description' => 'jakis krótki opis',
                'localization' => 'Kielce',
                'cover' => 'images/offerCovers/1W2dV4ZMkQrIoDXYB3T645GyOnNzJrvj27f7UU64.webp',
                'category_id' => '2',
                'price' => 10,
                'delivery_time' => '2-3 dni',
            ],
            [
                'user_id' => 5,
                'title' => 'Jakis tam tytul',
                'description' => 'jakis krótki opis',
                'localization' => 'Kielce',
                'cover' => 'images/offerCovers/1W2dV4ZMkQrIoDXYB3T645GyOnNzJrvj27f7UU64.webp',
                'category_id' => '2',
                'price' => 10,
                'delivery_time' => '2-3 dni',
            ],
            [
                'user_id' => 1,
                'title' => 'Jakis tam tytul',
                'description' => 'jakis krótki opis',
                'localization' => 'Kielce',
                'cover' => 'images/offerCovers/1W2dV4ZMkQrIoDXYB3T645GyOnNzJrvj27f7UU64.webp',
                'category_id' => '2',
                'price' => 10,
                'delivery_time' => '2-3 dni',
            ],
            [
                'user_id' => 2,
                'title' => 'Jakis tam tytul',
                'description' => 'jakis krótki opis',
                'localization' => 'Kielce',
                'cover' => 'images/offerCovers/1W2dV4ZMkQrIoDXYB3T645GyOnNzJrvj27f7UU64.webp',
                'category_id' => '2',
                'price' => 10,
                'delivery_time' => '2-3 dni',
            ],
            [
                'user_id' => 3,
                'title' => 'Jakis tam tytul',
                'description' => 'jakis krótki opis',
                'localization' => 'Kielce',
                'cover' => 'images/offerCovers/1W2dV4ZMkQrIoDXYB3T645GyOnNzJrvj27f7UU64.webp',
                'category_id' => '2',
                'price' => 10,
                'delivery_time' => '2-3 dni',
            ],

            [
                'user_id' => 4,
                'title' => 'Jakis tam tytul',
                'description' => 'jakis krótki opis',
                'localization' => 'Kielce',
                'cover' => 'images/offerCovers/1W2dV4ZMkQrIoDXYB3T645GyOnNzJrvj27f7UU64.webp',
                'category_id' => '2',
                'price' => 10,
                'delivery_time' => '2-3 dni',
            ],
            [
                'user_id' => 5,
                'title' => 'Jakis tam tytul',
                'description' => 'jakis krótki opis',
                'localization' => 'Kielce',
                'cover' => 'images/offerCovers/1W2dV4ZMkQrIoDXYB3T645GyOnNzJrvj27f7UU64.webp',
                'category_id' => '2',
                'price' => 10,
                'delivery_time' => '2-3 dni',
            ],
            [
                'user_id' => 1,
                'title' => 'Jakis tam tytul',
                'description' => 'jakis krótki opis',
                'localization' => 'Kielce',
                'cover' => 'images/offerCovers/1W2dV4ZMkQrIoDXYB3T645GyOnNzJrvj27f7UU64.webp',
                'category_id' => '3',
                'price' => 10,
                'delivery_time' => '2-3 dni',
            ],
            [
                'user_id' => 2,
                'title' => 'Jakis tam tytul',
                'description' => 'jakis krótki opis',
                'localization' => 'Kielce',
                'cover' => 'images/offerCovers/1W2dV4ZMkQrIoDXYB3T645GyOnNzJrvj27f7UU64.webp',
                'category_id' => '3',
                'price' => 10,
                'delivery_time' => '2-3 dni',
            ],
            [
                'user_id' => 3,
                'title' => 'Jakis tam tytul',
                'description' => 'jakis krótki opis',
                'localization' => 'Kielce',
                'cover' => 'images/offerCovers/1W2dV4ZMkQrIoDXYB3T645GyOnNzJrvj27f7UU64.webp',
                'category_id' => '4',
                'price' => 10,
                'delivery_time' => '2-3 dni',
            ],
            [
                'user_id' => 4,
                'title' => 'Jakis tam tytul',
                'description' => 'jakis krótki opis',
                'localization' => 'Kielce',
                'cover' => 'images/offerCovers/1W2dV4ZMkQrIoDXYB3T645GyOnNzJrvj27f7UU64.webp',
                'category_id' => '4',
                'price' => 10,
                'delivery_time' => '2-3 dni',
            ],
            [
                'user_id' => 5,
                'title' => 'Jakis tam tytul',
                'description' => 'jakis krótki opis',
                'localization' => 'Kielce',
                'cover' => 'images/offerCovers/1W2dV4ZMkQrIoDXYB3T645GyOnNzJrvj27f7UU64.webp',
                'category_id' => '4',
                'price' => 10,
                'delivery_time' => '2-3 dni',
            ],
            [
                'user_id' => 2,
                'title' => 'Jakis tam tytul',
                'description' => 'jakis krótki opis',
                'localization' => 'Kielce',
                'cover' => 'images/offerCovers/1W2dV4ZMkQrIoDXYB3T645GyOnNzJrvj27f7UU64.webp',
                'category_id' => '4',
                'price' => 10,
                'delivery_time' => '2-3 dni',
            ],
            [
                'user_id' => 3,
                'title' => 'Jakis tam tytul',
                'description' => 'jakis krótki opis',
                'localization' => 'Kielce',
                'cover' => 'images/offerCovers/1W2dV4ZMkQrIoDXYB3T645GyOnNzJrvj27f7UU64.webp',
                'category_id' => '4',
                'price' => 10,
                'delivery_time' => '2-3 dni',
            ],
            [
                'user_id' => 4,
                'title' => 'Jakis tam tytul',
                'description' => 'jakis krótki opis',
                'localization' => 'Kielce',
                'cover' => 'images/offerCovers/1W2dV4ZMkQrIoDXYB3T645GyOnNzJrvj27f7UU64.webp',
                'category_id' => '5',
                'price' => 10,
                'delivery_time' => '2-3 dni',
            ],
            [
                'user_id' => 5,
                'title' => 'Jakis tam tytul',
                'description' => 'jakis krótki opis',
                'localization' => 'Kielce',
                'cover' => 'images/offerCovers/1W2dV4ZMkQrIoDXYB3T645GyOnNzJrvj27f7UU64.webp',
                'category_id' => '5',
                'price' => 10,
                'delivery_time' => '2-3 dni',
            ],
            [
                'user_id' => 1,
                'title' => 'Jakis tam tytul',
                'description' => 'jakis krótki opis',
                'localization' => 'Kielce',
                'cover' => 'images/offerCovers/1W2dV4ZMkQrIoDXYB3T645GyOnNzJrvj27f7UU64.webp',
                'category_id' => '6',
                'price' => 10,
                'delivery_time' => '2-3 dni',
            ],
        ]);
    }
}
